In [3]:
import pandas as pd
df = pd.read_csv("weather_data.csv")
df

          day  temperature  windspeed  event
0  01-01-2017           32          6   Rain
1  01-02-2017           35          7  Sunny
2  01-03-2017           28          2   Snow
3  01-04-2017           24          7   Snow
4  01-05-2017           32          4   Rain
5  01-06-2017           31          2  Sunny

In [6]:
weather_data = {
    'day': ['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/6/2017'],
    'temperature': [32,35,28,24,32,31],
    'windspeed': [6,7,2,7,4,2],
    'event': ['Rain', 'Sunny', 'Snow','Snow','Rain', 'Sunny']
}

df = pd.DataFrame(weather_data)
df = pd.read_csv("weather_data.csv")
df

          day  temperature  windspeed  event
0  01-01-2017           32          6   Rain
1  01-02-2017           35          7  Sunny
2  01-03-2017           28          2   Snow
3  01-04-2017           24          7   Snow
4  01-05-2017           32          4   Rain
5  01-06-2017           31          2  Sunny

In [8]:
df.shape

(6, 4)

In [11]:
rows, columns = df.shape
rows

6

In [13]:
df.head()

          day  temperature  windspeed  event
0  01-01-2017           32          6   Rain
1  01-02-2017           35          7  Sunny
2  01-03-2017           28          2   Snow
3  01-04-2017           24          7   Snow
4  01-05-2017           32          4   Rain

In [15]:
df.head(2)

          day  temperature  windspeed  event
0  01-01-2017           32          6   Rain
1  01-02-2017           35          7  Sunny

In [17]:
df.head(5)

          day  temperature  windspeed  event
0  01-01-2017           32          6   Rain
1  01-02-2017           35          7  Sunny
2  01-03-2017           28          2   Snow
3  01-04-2017           24          7   Snow
4  01-05-2017           32          4   Rain

In [18]:
df.tail(3)

          day  temperature  windspeed  event
3  01-04-2017           24          7   Snow
4  01-05-2017           32          4   Rain
5  01-06-2017           31          2  Sunny

In [20]:
df[2:5]

          day  temperature  windspeed event
2  01-03-2017           28          2  Snow
3  01-04-2017           24          7  Snow
4  01-05-2017           32          4  Rain

In [22]:
df

          day  temperature  windspeed  event
0  01-01-2017           32          6   Rain
1  01-02-2017           35          7  Sunny
2  01-03-2017           28          2   Snow
3  01-04-2017           24          7   Snow
4  01-05-2017           32          4   Rain
5  01-06-2017           31          2  Sunny

In [24]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [26]:
df.day

0    01-01-2017
1    01-02-2017
2    01-03-2017
3    01-04-2017
4    01-05-2017
5    01-06-2017
Name: day, dtype: object

In [28]:
df.event

0     Rain
1    Sunny
2     Snow
3     Snow
4     Rain
5    Sunny
Name: event, dtype: object

In [30]:
type(df['event'])

pandas.core.series.Series

In [35]:
df[['event','day']]

   event         day
0   Rain  01-01-2017
1  Sunny  01-02-2017
2   Snow  01-03-2017
3   Snow  01-04-2017
4   Rain  01-05-2017
5  Sunny  01-06-2017

In [36]:
df['temperature'].max()

35

In [41]:
df['temperature'].min()

24

In [44]:
df['temperature'].mean()

np.float64(30.333333333333332)

In [46]:
df['temperature'].sum()

np.int64(182)

In [48]:
df.describe()

       temperature  windspeed
count     6.000000   6.000000
mean     30.333333   4.666667
std       3.829708   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

In [ ]:
df[df.temperature>=32]

In [52]:
df[df.temperature==df['temperature'].max()]

          day  temperature  windspeed  event
1  01-02-2017           35          7  Sunny

In [58]:
# Temperature 30 se zyada
df[df.temperature > 30]

# Event Rain ho
df[df.event == "Rain"]

# Windspeed 5 se kam ho
df[df.windspeed < 5]

# Temperature 32 ho
df[df.temperature == 32]

# IMPORTANT:
# Ye 4 alag-alag filters hain, ek hi filter nahi.
# Har line independently DataFrame ko filter karti hai.
# Jupyter Notebook by default sirf LAST line ka output dikhata hai.
# Isliye upar wali conditions (jaise windspeed < 5) last output par apply nahi hoti hain.
# Agar multiple conditions ko ek saath apply karna ho, to '&' (AND) ya '|' (OR) use karna hoga.
# Real projects me agar question me multiple requirements di gayi hon, to combined filtering use karna best practice hai.

          day  temperature  windspeed event
0  01-01-2017           32          6  Rain
4  01-05-2017           32          4  Rain

In [59]:
# IMPORTANT:
# Sabhi conditions ek saath apply ho rahi hain.
# '&' ka matlab AND hai, yani har condition True honi chahiye.
# Agar ek bhi condition False hui, to wo row output me nahi aayegi.
# Ye approach tab use hoti hai jab question me multiple requirements di gayi hon.
# Real-world data analysis me isi tarah combined filtering use ki jati hai.
# Multiple conditions ko ek hi result me accurately filter karne ka ye standard tareeka hai.


df[
    (df.temperature > 30) &      # Temperature 30 se zyada ho
    (df.event == "Rain") &       # Event Rain ho
    (df.windspeed < 5) &         # Windspeed 5 se kam ho
    (df.temperature == 32)       # Temperature exactly 32 ho
]

          day  temperature  windspeed event
4  01-05-2017           32          4  Rain

In [56]:
df

          day  temperature  windspeed  event
0  01-01-2017           32          6   Rain
1  01-02-2017           35          7  Sunny
2  01-03-2017           28          2   Snow
3  01-04-2017           24          7   Snow
4  01-05-2017           32          4   Rain
5  01-06-2017           31          2  Sunny

## For Operations
https://pandas.pydata.org/docs/reference/api/pandas.Series.html

In [13]:
df

            temperature  windspeed  event
day
01-01-2017           32          6   Rain
01-02-2017           35          7  Sunny
01-03-2017           28          2   Snow
01-04-2017           24          7   Snow
01-05-2017           32          4   Rain
01-06-2017           31          2  Sunny

In [18]:
df.head()

            temperature  windspeed  event
day
01-01-2017           32          6   Rain
01-02-2017           35          7  Sunny
01-03-2017           28          2   Snow
01-04-2017           24          7   Snow
01-05-2017           32          4   Rain

In [20]:
df.columns

Index(['temperature', 'windspeed', 'event'], dtype='object')

In [24]:
df.loc['01-03-2017']   # '01-03-2017' date (index) wali row ko select karta hai

temperature      28
windspeed         2
event          Snow
Name: 01-03-2017, dtype: object

In [27]:
df.reset_index(inplace=True)   # Index ko wapas normal column me convert karta hai aur default numeric index (0, 1, 2, ...) laga deta hai

df   # Updated DataFrame ko display karta hai

   level_0  index         day  temperature  windspeed  event
0        0      0  01-01-2017           32          6   Rain
1        1      1  01-02-2017           35          7  Sunny
2        2      2  01-03-2017           28          2   Snow
3        3      3  01-04-2017           24          7   Snow
4        4      4  01-05-2017           32          4   Rain
5        5      5  01-06-2017           31          2  Sunny