## Different Ways Of Creating Dataframe

## Using csv

In [4]:
import pandas as pd
df = pd.read_csv("weather_data.csv")
df

          day  temperature  windspeed  event
0  01-01-2017           32          6   Rain
1  01-02-2017           35          7  Sunny
2  01-03-2017           28          2   Snow
3  01-04-2017           24          7   Snow
4  01-05-2017           32          4   Rain
5  01-06-2017           31          2  Sunny

## Using Excel

In [6]:
df = pd.read_excel("weather_data.xlsx")
df

         day  temperature  windspeed  event
0 2017-01-01           32          6   Rain
1 2017-01-02           35          7  Sunny
2 2017-01-03           28          2   Snow

## Using Dictionary

In [8]:
weather_data = {
    'day': ['1/1/2017','1/2/2017','1/3/2017'],
    'temperature': [32,35,28],
    'windspeed': [6,7,2],
    'event': ['Rain', 'Sunny', 'Snow']
}

df = pd.DataFrame(weather_data)
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

## Using Tuples

In [12]:
weather_data = [
    ('01/01/2026', 32, 6, 'Rain'),   # Day, Temperature, Windspeed, Event
    ('01/02/2026', 25, 7, 'Sunny'),  # Day, Temperature, Windspeed, Event
    ('01/03/2026', 28, 2, 'Snow')    # Day, Temperature, Windspeed, Event
]

# List ko DataFrame me convert karna aur column names dena
df = pd.DataFrame(
    weather_data,
    columns=["day", "temperature", "windspeed", "event"]
)

df   # DataFrame ko display karta hai

          day  temperature  windspeed  event
0  01/01/2026           32          6   Rain
1  01/02/2026           25          7  Sunny
2  01/03/2026           28          2   Snow

## Using list of dictionaries

In [13]:
weather_data = [
    {'day': '1/1/2017', 'temperature': 32, 'windspeed': 6, 'event': 'Rain'},
    {'day': '1/2/2017', 'temperature': 35, 'windspeed': 7, 'event': 'Sunny'},
    {'day': '1/3/2017', 'temperature': 28, 'windspeed': 2, 'event': 'Snow'},
    
]

df = pd.DataFrame(data=weather_data, columns=['day','temperature','windspeed','event'])
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow